config/routes.rb
ProjectNightMeta::Application.routes.draw do

   root 'home#index'
   resources :projects, only: [:show]
   resources :members, only: [:show]

  get '/about'    => 'home#about'
  put '/location/change'  => 'home#change_city'
  get '/signin'        => 'sessions#index'
  get '/user/signout'  => 'sessions#signout'
  get '/auth/:provider/callback' => 'sessions#create'

  get  '/groups/:id'      => 'groups#show'
  get  '/projects/:id'    => 'projects#show'
  get  '/members/:id'     => 'members#show'
  get  '/members/:id/manage'   => 'members#manage'

  get  '/user/account'                 => 'accounts#index'
  post '/user/account/update/profile'  => 'accounts#update_profile'
  delete '/user/account/delete'        => 'accounts#delete'

  get  '/user/groups'       => 'user_groups#index'
  post '/user/groups/sync'  => 'user_groups#sync'

  get  '/user/projects'        => 'user_projects#index'
  put  '/user/projects/:id/toggle'  => 'user_projects#toggle_visible'
  get  '/user/projects/new'    => 'user_projects#new'
  post '/user/projects'        => 'user_projects#create'
  get  '/user/projects/:id/edit' => 'user_projects#edit'
  put  '/user/projects/:id'      => 'user_projects#update'
  put  '/user/projects/:id/doaction'      => 'user_projects#doaction'
  delete '/user/projects/:id'    => 'user_projects#delete'
  post '/user/projects/sync'   => 'user_projects#sync'
  put  '/user/projects/:id/add/contributor' => 'user_projects#add_contributor'
  put  '/user/projects/:id/remove/contributor' => 'user_projects#remove_contributor'

  

end

app/models/project.rb
class Project < ActiveRecord::Base
  before_destroy :destroy_project_users
  validates_presence_of   :full_name

  has_many :project_users, class_name: 'UserProject', foreign_key: :project_id, primary_key: :id
  has_many :contributors, through: :project_users, source: :user
  belongs_to :user, class_name: 'User', foreign_key: :user_id, primary_key: :id


  # class methods

  def self.build_with(github_repo_hash)
    project = new()
    project.refresh_with(github_repo_hash)

    project
  end

  def self.import_with(github_repo_hash)
    h = github_repo_hash
    if exists?(["github_id=?", h["id"]])
      project = find_by_github_id(h["id"])
      project.refresh_with(h)
    else
      project = build_with(h)
    end
    project.save!
    project
  end


  # instance methods

  def add_contributor(user)
    return user if user.contributor_of?(self)
    self.contributors << user
    user
  end

  def add_maintainer(user)
    if user_id.blank? || user_id == 0
      # no owner, set the project owner now
      self.user = user
      self.city = user.city
      self.state = user.state
      self.country = user.country
      save!
    end

    assoc = UserProject.entry(user, self)
    # found existing entry
    if assoc
      if !assoc.is_maintainer
        # make user a project maintainer - transfer of maintainership?
        assoc.is_maintainer = true
        assoc.save!
      end
      return user
    end

    # create new entry
    assoc = UserProject.new
    assoc.user = user
    assoc.project = self
    assoc.is_maintainer = true
    assoc.save!

    user
  end

  def remove(user)
    return false if user.owns(self) # should never remove owner

    assoc = UserProject.entry(user, self)
    assoc.destroy! if assoc
    true
  end

  def refresh_with(github_repo_hash)
    h = github_repo_hash

    self.github_id = h["id"]
    self.owner_id = h["owner"]["id"]
    self.private = h["private"]
    self.fork = h["fork"]
    self.name = h["name"]
    self.full_name = h["full_name"]
    self.description = h["description"]
    self.language = h["language"]
    self.homepage = h["homepage"]
    self.html_url = h["html_url"]
    self.created_at = h["created_at"]
  end

  def maintainers
    a = project_users.select { | each | each.is_maintainer }  
    a.collect { | each | each.user }
  end

  def is_github
    !github_id.blank?
  end

  def is_hidden
    !visible
  end


  protected
    def destroy_project_users
      project_users.each { | assoc |
        assoc.destroy!
      }
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  # GET /projects/:id
  def show
    @project = Project.find params[:id]

    respond_to do |format|
      format.html {
        unless @project.visible
          redirect_to "/404"
          return
        end
        @maintainers = @project.maintainers
        @title = "Project"
      }
      format.json {
        raise ActiveRecord::RecordNotFound unless @project.visible
        render json: @project
      }
    end

  rescue ActiveRecord::RecordNotFound => e
    log_error_and_redirect_to(e, '/404')
  rescue Exception => e
    log_error_and_redirect_to(e, '/')
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_project.html.erb
<div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
  <div class='well'>
    <div class='row'>
      <div class='col-md-4'>
        <%= link_to image_tag(project.user.mu_thumb_link, class: 'img-thumb'), member_path(project.user) %>
      </div>
      <div class='col-md-8'>
        <%= link_to content_tag(:h4, project.name), project_path(project) %>
        <p>
          <% if project.is_github -%>
            <img src="/images/GitHub-Mark-32px.png" height="16px" title="GitHub project" />
          <% else -%>
            <span class="glyphicon glyphicon-folder-open" title="Project"></span>
          <% end -%>
          <small><%= project.language %></small>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="jumbotron">
<h2><% if @project.is_github -%>
    <img src="/images/GitHub-Mark-32px.png" title="GitHub project" />
  <% else -%>
    <span class="glyphicon glyphicon-folder-open" title="Project"></span>
  <% end -%>
  &nbsp;<%= @project.full_name %>
</h2>

<div class="container">
  <p><%= @project.description %></p>
  <% if @project.is_github %>
    <p class="project-lang"><%= @project.language %> &nbsp; fork: <%= @project.fork %> &nbsp; <a href="<%= @project.html_url %>">Fork on GitHub</a></p>
  <% end %>
</div>
</div>

<div class="contributors">
  <h3><span class="glyphicon glyphicon-user"></span> Contributors</h3>
  <ul class="ul-thumb">
  <% @project.contributors.each do | user | %>
    <li>
      <a href="/members/<%= user.id %>" title="<%= get_user_name(user, @maintainers) %>"><img class="img-thumbnail thumb-height" src="<%= user.mu_thumb_link %>" alt="<%= get_user_name(user, @maintainers) %>" /></a>
    </li>
  <% end %>
  </ul>
</div>

<div class="groups">
  <h3><span class="glyphicon glyphicon-th-large"></span> Find <%= @project.user.mu_name %> at these Meetup Groups</h3>
  <div class="row">
  <% @project.user.groups.each do | group | %>
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
    <div class="thumbnail">
      <a href="/groups/<%= group.urlname %>">
      <div class="caption">
        <img class="img-rounded thumb-height" src="<%= group.mu_thumb_link %>" alt="photo"/>
        <div class="caption">
        <%= group.mu_name %>
        </div>
      </div>
      </a>
    </div>
  </div>
  <% end %>
  </div>
</div>